<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>339b4c65-762e-4328-8755-d5a7d37038b8</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Azure.Search.Documents" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="7.0.0" />
    <PackageReference Include="UglyToad.PdfPig" Version="0.1.9-alpha001-patch1" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.23.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.1-preview.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
  </ItemGroup>

</Project>
